# Consumer module config

# RabbitMQ
rabbit.host=localhost
rabbit.port=5672
rabbit.username=sms
rabbit.password=sms@123
rabbit.queue=sms-queue
rabbit.delayQueue=sms-queue-delay

# Redis
redis.host=localhost
redis.port=6379
sms.tps=1

# DB
db.url=jdbc:postgresql://localhost:5332/postgres?sslmode=disable
db.username=smsgw
db.password=smsgw

# Gateway
gateway.url=https://smsgw.vnpaytest.vn/smsgw/sendSms
secret.key=5c6b322e-5d49-4ac3-9fab-1f2d9f3322d1

# Retry
sms.retry.max=3
sms.retry.delay.ms=1000
