spring.application.name=producer-sms

# Port cho server
server.port=8022

# Database
spring.datasource.url=jdbc:postgresql://localhost:5332/postgres?sslmode=disable
spring.datasource.username=smsgw
spring.datasource.password=smsgw
spring.datasource.driver-class-name=org.postgresql.Driver

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=sms
spring.rabbitmq.password=sms@123

# Optional - rabbitmq
spring.rabbitmq.virtual-host=/
spring.rabbitmq.listener.simple.concurrency=3
spring.rabbitmq.listener.simple.max-concurrency=10
spring.rabbitmq.listener.simple.acknowledge-mode=auto

# exchange - routing key
app.rabbitmq.exchange=sms-exchange
app.rabbitmq.queue=sms-queue
app.rabbitmq.routing-key=sms-routing-key

# Time scan sms
sms.time.scan=10000