# API module configuration
server.port=8021

# Database
db.url=jdbc:postgresql://localhost:5332/postgres?sslmode=disable
db.username=smsgw
db.password=smsgw

# Connection pool
pool.maximumPoolSize=10
