# Producer module config

# RabbitMQ
rabbit.host=localhost
rabbit.port=5672
rabbit.username=sms
rabbit.password=sms@123
rabbit.exchange=sms-exchange
rabbit.queue=sms-queue
rabbit.routingKey=sms-routing-key

# DB
db.url=jdbc:postgresql://localhost:5332/postgres?sslmode=disable
db.username=smsgw
db.password=smsgw

# scheduler
scan.interval.ms=5000

# number thread
scan.thread=10
